import 'package:get/get.dart';

// 'en', 'hi', 'mr', 'ta', 'te', 'kn', 'pa', 'as', 'bn', 'gu', 'hr'
class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => //json;
      {
        "en_IN": {
          "checkAndTryInternetConnectivity":
              "Please check your network connectivity and try again",
          "connectionError": "Connection Error",
          'noRecordFound': 'No Record Found',
          'year': '%s1 Years',
          'min': 'Min',
          'talkONCall': 'Talk On Call',
          'title': 'Talk to an Astrologer',
          "sortBy": 'Sort By',
          'expHTL': 'Experience- High To Low',
          'expLTH': 'Experience- Low To High',
          'prcHTL': 'Price- High To Low',
          'prcLTH': 'Price- Low To High',
          'searchHintTxt': 'Search By Name, Language and Skills',
          'reset': 'Reset',
          'done': 'Done',
          'filter': 'Filters',
          'language': 'Languages',
          'skills': 'Skills',
          'dailyPanchang': 'Daily Panchang',
          'date': 'Date:',
          'location': 'Location:',
          'panchangMsg':
              'India is a country known for its festival but knowing the exact dates can sometimes be difficult. To ensure you do not miss out on the critical dates we bring you the daily panchang.',
          'tithi':'Tithi',
          'tithiNumber':'Tithi Number :',
          'tithiName':'Tithi Name :',
          'special':'Special :',
          'summary':'Summary :',
          'deity':'Diety :',
          'endTime':'End Time :',
          'nakshatra':'Nakshatra',
          'nakshatraNumber':'Nakshatra Number :',
          'nakshatraName':'Nakshatra Name :',
          'ruler':'Ruler:',
          'yog':'Yog',
          'yogNumber':'Yog Number :',
          'yogName':'Yog Name :',
          'meaning':'Meaning :',
          'karan':'Karan',
          'karanNumber':'Karan Number :',
          'karanName':'Karan Name :',
          'hinduMaah':'Hindu Maah',
          'purnimanta':'Purnimanta :',
          'amanta':'Amanta :',
          'paksha':'Paksha :',
          'ritu':'Ritu :',
          'sunSign':'Sun Sign :',
          'moonSign':'Moon Sign',
          'ayana':'Ayana :',
          'panchangYog':'Panchang yog :',
          'vikramSamvat':'Vikram Samvat :',
          'shakaSamvat':'Shaka Samvat :',
          'shakaSamvatName':'Shaka Samvat Name :',
          'dishaShool':'Disha Shool :',
          'dishaShoolRemedies':'Disha Shool Remedies :',
          'nakShool':'Nak Shool :',
          'moonNivas':'Moon Nivas :',
          'abhijitMuhurta':'Abhijit Muhurta',
          'start':'Start :',
          'end':'End :',
          'rahukaal':'Rahukaal',
          'gulikaal':'Gulikaal',
          'yamghantKaal':'Yamghant Kaal',
          'endTimeValue':'%s1 hr %s2 min %s3 sec',
        },
        "hi_IN": {
          "checkAndTryInternetConnectivity":
          "Please check your network connectivity and try again",
          "connectionError": "Connection Error",
          'noRecordFound': 'No Record Found',
          'year': '%s1 Years',
          'min': 'Min',
          'talkONCall': 'Talk On Call',
          'title': 'Talk to an Astrologer',
          "sortBy": 'Sort By',
          'expHTL': 'Experience- High To Low',
          'expLTH': 'Experience- Low To High',
          'prcHTL': 'Price- High To Low',
          'prcLTH': 'Price- Low To High',
          'searchHintTxt': 'Search By Name, Language and Skills',
          'reset': 'Reset',
          'done': 'Done',
          'filter': 'Filters',
          'language': 'Languages',
          'skills': 'Skills',
          'dailyPanchang': 'Daily Panchang',
          'date': 'Date:',
          'location': 'Location:',
          'panchangMsg':
          'India is a country known for its festival but knowing the exact dates can sometimes be difficult. To ensure you do not miss out on the critical dates we bring you the daily panchang.',
          'tithi':'Tithi',
          'tithiNumber':'Tithi Number :',
          'tithiName':'Tithi Name :',
          'special':'Special :',
          'summary':'Summary :',
          'deity':'Diety :',
          'endTime':'End Time :',
          'nakshatra':'Nakshatra',
          'nakshatraNumber':'Nakshatra Number :',
          'nakshatraName':'Nakshatra Name :',
          'ruler':'Ruler:',
          'yog':'Yog',
          'yogNumber':'Yog Number :',
          'yogName':'Yog Name :',
          'meaning':'Meaning :',
          'karan':'Karan',
          'karanNumber':'Karan Number :',
          'karanName':'Karan Name :',
          'hinduMaah':'Hindu Maah',
          'purnimanta':'Purnimanta :',
          'amanta':'Amanta :',
          'paksha':'Paksha :',
          'ritu':'Ritu :',
          'sunSign':'Sun Sign :',
          'moonSign':'Moon Sign',
          'ayana':'Ayana :',
          'panchangYog':'Panchang yog :',
          'vikramSamvat':'Vikram Samvat :',
          'shakaSamvat':'Shaka Samvat :',
          'shakaSamvatName':'Shaka Samvat Name :',
          'dishaShool':'Disha Shool :',
          'dishaShoolRemedies':'Disha Shool Remedies :',
          'nakShool':'Nak Shool :',
          'moonNivas':'Moon Nivas :',
          'abhijitMuhurta':'Abhijit Muhurta',
          'start':'Start :',
          'end':'End :',
          'rahukaal':'Rahukaal',
          'gulikaal':'Gulikaal',
          'yamghantKaal':'Yamghant Kaal',
          'endTimeValue':'%s1 hr %s2 min %s3 sec',
        },
      };
}
